tests/pkcs11mtt.c, tests/pkcs11test.c
Fix for test pin to be at least 14-characters as required by FIPS HMAC. ZD13122
=> Fix for FIPS and pin length

src/crypto.c, src/internal.c
Set the common label for the public key directly after creation rather than after private key has been added.
Initialize ecc object before decoding ECC private key. Fix comments.
=> Fixes: setting of label, init ecc object

src/internal.c
Always flush successful writes to ensure data makes it to storage as soon as possible.
=> Flush store writes

src/crypto.c, src/internal.c, src/slot.c, wolfpkcs11/internal.h
- WOLFSSL_USER_SETTINGS to avoid including wolfssl/options.h
- WOLFPKCS11_USER_SETTINGS to avoid including wolfPKCS11/options.h
- NO_PKCS11_TIME to make wc_GetTime() optional (it disables bruteforce protections on token login)
=> Added compile-time defines for embedded builds

src/internal.c
When compiling with wolfboot, I spotted the following:
```
lib/wolfPKCS11/src/internal.c: In function 'WP11_Object_SetEcKey':
lib/wolfPKCS11/src/internal.c:4725:26: error: passing argument 1 of 'SetMPI' from incompatible pointer type [-Werror=incompatible-pointer-types]
4725 |             ret = SetMPI(&key->k, data[1], (int)len[1]);
|                          ^~~~~~~
|                          |
|                          mp_int (*)[1] {aka sp_int (*)[1]}
lib/wolfPKCS11/src/internal.c:4506:27: note: expected 'mp_int *' {aka 'sp_int *'} but argument is of type 'mp_int (*)[1]' {aka 'sp_int (*)[1]'}
4506 | static int SetMPI(mp_int* mpi, unsigned char* data, int len)
|                   ~~~~~~~~^~~
lib/wolfPKCS11/src/internal.c: In function 'EcObject_GetAttr': …
```
=> Fixed argument passing in SetMPI/GetMPIData

src/internal.c
When compiling with RSA on but NO_DH, the following errors occur:
```
lib/wolfPKCS11/src/internal.c: In function 'WP11_Object_Free':
lib/wolfPKCS11/src/internal.c:4461:9: error: implicit declaration of function 'wc_FreeDhKey'; did you mean 'wc_FreeRsaKey'? [-Werror=implicit-function-declaration]
4461 |         wc_FreeDhKey(&object->data.dhKey.params);
|         ^~~~~~~~~~~~
|         wc_FreeRsaKey
lib/wolfPKCS11/src/internal.c:4461:35: error: 'union <anonymous>' has no member named 'dhKey'
4461 |         wc_FreeDhKey(&object->data.dhKey.params);
|     
```
This patch guards the offending code with the right option `NO_DH` instead of `NO_RSA`.
=> Fixed NO_DH ifdef gate when freeing PKCS11 object

src/crypto.c, src/internal.c, src/slot.c, tests/README.md, tests/include.am, tests/pkcs11mtt.c, tests/pkcs11test.c, wolfpkcs11/internal.h
Sean, David,
Here are the updates for the C_WrapKey/C_UnwrapKey addition that we (BRN) needs.  Please consider adding this.
As discussed on the call, we haven't added unit tests; however, Todd indicated that you would be willing.  We tested by implementation compatibility checks in a larger use case. All possible return codes haven't been tested.
=> Add support for wrap/unwrap RSA with aes_cbc_pad.

.github/workflows/unit-test.yml, configure.ac, m4/ax_create_generic_config.m4, m4/ax_harden_compiler_flags.m4, m4/ax_pthread.m4, m4/ax_tls.m4, tests/pkcs11mtt.c, tests/pkcs11str.c, tests/pkcs11test.c, tests/unit.h
* Fix handle leak with `test_wrap_unwrap_key` (from https://github.com/wolfSSL/wolfPKCS11/pull/15)'
* Fix `function declaration isn’t a prototype`.
* Fix warnings from ./autogen.sh. Updated m4 macros.
* Add wolfPKCS11 GitHub CI action.
=> Fix for test_wrap_unwrap_key handle leak. Add GitHub CI action

tests/pkcs11mtt.c, tests/pkcs11str.c, tests/pkcs11test.c
Portability fixes. Added `NO_MAIN_DRIVER`. Support for `SINGLE_THREADED`. Add `static` to some globals.
=> Portability fixes

src/internal.c, tests/pkcs11mtt.c, tests/pkcs11str.c, tests/pkcs11test.c, wolfpkcs11/internal.h, wolfpkcs11/pkcs11.h
* Fix for portability case where `XREALLOC` is not available
* Add support for custom setenv/get env using `WOLFPKCS11_USER_ENV`.
* For embedded systems allow pin hashing using SHA2-256 vs script (which uses multiple MB of memory).
* Fix for final not being called after init in edge case pin failure.
=> Portability improvements for XREALLOC, XGETENV and pin hashing

src/crypto.c
Fix for `C_GetAttributeValue` incorrectly erroring with `CKR_ATTRIBUTE_VALUE_INVALID` when data == NULL. The `C_GetAttributeValue` should set length if data field is NULL.
=> Fix for `C_GetAttributeValue` when getting length (data==NULL)

src/crypto.c, tests/pkcs11test.c
Allow length retrieval even for fixed size attributes.
=> Allow C_GetAttributeValue to yield length of fixed size attributes

examples/add_cert.c, src/internal.c, tests/pkcs11test.c
Added test to verify login/logout behavior
=> Fix decode cert when store is enabled for login/logout reuse scenario

src/internal.c, wolfpkcs11/store.h
* Fix to use accurate NV sizes
* Add support for expanding NV (delete and recreate) if its not large enough on write.
* Fix to support using X.509 certificate store on TPM NV. Was not functional, since type was missing from wolfPKCS11_Store_GetMaxSize.
ZD 18462
=> Fixes for TPM based NV storage

src/internal.c, wolfpkcs11/store.h
Restore compatibility with `wolfPKCS11_Store_Open` and add new API `wolfPKCS11_Store_OpenSz` to support the new variable size argument (only required for use with TPM's).
Fixes wolfBoot regression on submodule update here: https://github.com/wolfSSL/wolfBoot/pull/533
=> Restore compatibility with `wolfPKCS11_Store_Open`

src/internal.c
Eliminate requirement to use `wolfPKCS11_Store_OpenSz` unless building with `WOLFPKCS11_TPM_STORE`.
=> Eliminate requirement to use `wolfPKCS11_Store_OpenSz`

src/slot.c, tests/pkcs11test.c
There are times where we don't want login to be required. This is now possible via `WOLFPKCS11_NO_LOGIN`.
=> Add option to disable `CKF_LOGIN_REQUIRED`

src/crypto.c, src/internal.c, tests/pkcs11test.c
Fixes the following things:
* Fix key wipe in `WP11_Object_SetEcKey`
* Fix AES CBC padding calculation
* Fix ECC derive key curve error
=> Crypto fixes

.github/workflows/unit-test.yml, configure.ac, src/crypto.c, src/internal.c, src/slot.c, tests/pkcs11test.c, wolfpkcs11/internal.h, wolfpkcs11/pkcs11.h
This adds HKDF derive and data functions, which are pretty much identical.
In theory `CKM_HKDF_DATA` should use a `CKO_DATA` class, in practice this doesn't happen when NSS uses wolfPKCS11 and for the default permissions it shouldn't make a difference.
=> HKDF derive / data

src/crypto.c, src/internal.c, tests/pkcs11mtt.c, tests/pkcs11test.c, wolfpkcs11/internal.h
This solves a few problems with the boolean attributes and the key permission flags. `CKA_EXTRACTABLE` was never set to true, so private key attributes could never be retrieved. This led to some other problems found which are now fixed:
* Boolean flags were stored in `WP11_Object.flags` but read from `WP11_Object.opFlag`, so they were never readable.
* Default boolean flags were never set for keys.
* `CKA_SENSITIVE` could change from true to false.
* Wrong boolean masks were used when setting some of the attributes.
* `test_attribute_get` would pass when there is a failure.
* Unwrap attribute setter got mixed with wrap.
Note: The `WP11_Object` type will keep the `flags` variable but it is now unused. It needs to stay because it may have been stored and could be loaded in from somewhere. …
=> Fix boolean attributes and permissions

src/crypto.c, src/internal.c, src/slot.c, tests/pkcs11mtt.c, tests/pkcs11test.c, wolfpkcs11/internal.h, wolfpkcs11/pkcs11.h
This implements the following mechanisms into `C_DeriveKey`:
* `CKM_TLS12_KEY_AND_MAC_DERIVE`
* `CKM_TLS12_MASTER_KEY_DERIVE`
* `CKM_TLS12_MASTER_KEY_DERIVE_DH`
=> Implement CKM_TLS12_* for C_DeriveKey

src/internal.c
This includes:
* Calling `wc_SetSeed_Cb` (also calling `wolfCrypt_Init`).
* Allowing for older versions of `ecc_key` struct to work.
* Using `PRIVATE_KEY_UNLOCK` / `PRIVATE_KEY_LOCK` where needed.
* Removing call to missing `wc_CmacFree` for FIPS < 5.3
=> Fixes required for FIPSv5 / v6 support

src/crypto.c, src/internal.c, src/slot.c, wolfpkcs11/internal.h, wolfpkcs11/pkcs11.h
- Advertise CKM_SSL3_MASTER_KEY_DERIVE even though we don't implement it. It is used by NSS to initially choose a slot that can support TLS resumption even though later the correct (TLS >=1.2) key derivation mechanism is selected. The relevant code is in `tls13_RecoverWrappedSharedSecret`.
- Increase `WP11_SESSION_OBJECT_CNT_MAX` and `WP11_SESSION_CNT_MAX`
- Advertise `CKF_USER_PIN_INITIALIZED` since we don't require login for NSS
- Add CKM_GENERIC_SECRET_KEY_GEN
- C_Login: accept a zero length pin
- Increase `WP11_MAX_SYM_KEY_SZ` and add size checks
=> Misc fixes for Firefox

src/crypto.c, src/internal.c, tests/pkcs11test.c, wolfpkcs11/internal.h
When no public exponent is provided, we should use 65537. If we do not, when the key is loaded from the token during pin login, the ASN decode of the key will fail. This in-turn causes login to fail.
ZD 19876
=> Fix RSA with no public exponent

src/internal.c, tests/pkcs11test.c
When not provided, the RSA modulus should be calculated as p*q. This was not done and could cause errors.
ZD 19905
=> Calculate RSA modulus when not provided

src/crypto.c, src/internal.c, tests/pkcs11mtt.c, tests/pkcs11test.c, wolfpkcs11/store.h
Both NSS trust and general certificates need these.
Also:
* Fix storage for these attributes.
* Fix storage for NSS trust objects.
=> Add issuer, subject and serial to objects

src/internal.c, tests/pkcs11test.c
Fix 1: Fix bug in object search
A typo meant that the C_FindObject assumed that all objects were private.
Fix 2: Don't erase token if there is a load error
Token data load errors should probably error, not silently erase the  token.
There does not seem to be a good way to test this with our current test framework.
=> Fixes for nss

.github/workflows/clang-tidy.yml, .github/workflows/sanitizer-tests.yml, src/crypto.c, src/internal.c, src/slot.c, tests/pkcs11test.c
* Update tests so that they run in a matrix using NSS and TPM
* Fix leak and error handling when `SymmKeyLen` `ret != 0`
* Fix `CKA_SENSITIVE` handling for metadata (caused `SummKeyLen` issue)
* Fixed cases of duplicate successive bodys for if / switch statements
* Fixed some spelling errors
* Fixed potential library leak
* Fixed leak of issuer, serial and subject attributes
* Fixed type issues with CLang
* Fixed stack overflow in `test_op_state_fail`
* Fixed cleanup in `test_ecc_curve`
=> Fix new master CI tests for NSS

.github/workflows/unit-test.yml, .gitignore, configure.ac, src/internal.c, tests/include.am, tests/rsa_session_persistence_test.c
Fixes for TPM based RSA key reloading. ZD 20045. 
Improve `WP11_Rsa_GenerateKeyPair` exponent logic. 
Fix for missing HAVE_GETPID in random.h WC_RNG.
Remove internal.c include of pkcs11.h (done too early and is part of internal.h).
=> Fixes for TPM based RSA key reloading

.github/workflows/nss-cmsutil-test.yml, .github/workflows/nss-pdfsig-test.yml, .github/workflows/nss-ssltap-test.yml
Retain only on failure, and for 5 days.
=> Align GH Actions retention policy

src/crypto.c, src/internal.c
Fix for TPM NV to not try and allocate a zero length buffer. 
Fix for create failure not to leak storage. ZD 20306
=> Fixes for TPM NV

src/internal.c, wolfpkcs11/store.h
* Fix to properly remove TPM NV objects on "unstore".
* Fix for `WP11_Object_WrapTpmKey` that was incorrectly setting the `WP11_FLAG_TPM` for public keys. 
* Fix to make sure the loaded RSA/ECC public keys have their devId set to allow crypto callback.
* Improvement to immediately encrypt/wrap any RSA or ECC private keys with TPM and store them in NV that way. 
* Fix to better handle/recover from a TPM NV out of space scenario.
ZD 20306
=> Fixes and improvements for TPM NV

.github/workflows/alpine-architecture-tests.yml, .github/workflows/build-workflow.yml, .github/workflows/clang-tidy.yml, .github/workflows/debian-package-test.yml, .github/workflows/sanitizer-tests.yml, .github/workflows/wolfssl-v5.6.6-build-workflow.yml, README.md, src/crypto.c, src/internal.c, tests/pkcs11test.c, wolfpkcs11/internal.h
Fixes to properly unstore removed objects and to properly re-index them without leaving stray store objects. 
Fixes to prevent malloc(0) with zero size. 
Fix for AES Keywrap and added tests.
=> Cleanup unstore logic

.github/workflows/nss-cmsutil-test.yml, .github/workflows/nss-ssltap-test.yml, src/crypto.c, src/internal.c, src/wolfpkcs11.c, tests/pkcs11test.c, wolfpkcs11/pkcs11.h
The cmsutil and ssltap tests were not actually testing wolfPKCS11, and this wasn't clear until the GitHub Actions cached was purged. This caused them to start failing on all PRs.
This PR:
* Drops the usage of `pk12util`, this requires custom NSS functions that we probably cannot implement in FIPSv5
* Adds the `CKA_NSS_EMAIL` attribute for certificates (needed for `certutil`)
* Fixes issues in the NSS config string parser (required for `ssltap`)
- Empty quoted values aborted with error instead of skipping
- Values that were not surrounded with quotes broke the parser
* Fixes `ssltap` test not actually compiling / installing wolfPKCS11
=> Fix failing GitHub Actions tests

src/internal.c
This fixes some of the random failures in NSS's ssl_gtest. With the previous behavior, raw X9.63 data could coincidentally have a byte that matched `pointLen - i` and erroneously be treated as DER-encoded.
=> Fix NSS random failures

.github/workflows/nss-pk12util-test.yml, .github/workflows/unit-test.yml, configure.ac, examples/include.am, examples/nss_pkcs12_pbe_example.c, src/crypto.c, src/internal.c, src/slot.c, tests/pkcs11test.c, wolfpkcs11/internal.h, wolfpkcs11/pkcs11.h
This PR:
* Adds support for `CKM_NSS_PKCS12_PBE_SHA*_HMAC_KEY_GEN`
* Adds support for `CKM_PKCS5_PBKD2`
* Adds `CKA_NSS_DB` as an ignored attribute (to suppress errors)
* Adds support for PBKDF2 pin hashing
The first three are required to make NSS `pk12util` work. The last one is enabled by default for FIPS, but the options `--enable-pbkdf2` and `--pbkdf2-iterations` have been added to use it in other builds.
PBKDF2 for pin is set to 600,000 rounds by default, which is the OWASP recommendation.
=> Fix pk12util and add PBKDF2

.github/workflows/scan-build.yml, examples/obj_list.c, src/internal.c, tests/debug_test.c
=> Fix things found in scan-build

.github/workflows/nss-pk12util-debian-test.yml, src/internal.c, src/slot.c
When PBKDF2 is used for PIN handling, if the pin is too small, this produces an error. This breaks our ability to have empty PINs.
Instead, we used a padded empty value.
=> Fix empty PIN handling for FIPS
